{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "bac2019c_ba4c474a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1096442
      },
      "writtenOn": "2023-01-16T04:36:02Z",
      "side": 1,
      "message": "Not sure why 3.3, 3.4 CI failed. Seems unrelated? and by the way 3.3 \u0026 3.4 are now not supported?",
      "revId": "b15f143f8461f7c63604ba8e538b41e5d6245e4d",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    }
  ]
}